[global_tags]
  environment = "production"

[agent]
  interval = "10s"
  round_interval = true
  flush_interval = "10s"
  hostname = "telegraf"
  omit_hostname = false

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "irrigation_token_123"
  organization = "noone"
  bucket = "irrigation-automation"

[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = ["farm/weather"]
  client_id = "telegraf-weather"
  qos = 0
  data_format = "json"
  name_override = "weather"

[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = ["farm/zone/+/sensors"]
  client_id = "telegraf-zones"
  qos = 0
  data_format = "json"
  name_override = "zone_sensors"
